SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ACT_RU_TASK_View] AS SELECT ID_,PROC_INST_ID_,PROC_DEF_ID_,NAME_,DESCRIPTION_,ASSIGNEE_,CREATE_TIME_,SUSPENSION_STATE_,FORM_KEY_,TASK_TYPE_,TASK_BLOCK_TYPE_ FROM [ACT_RU_TASK];
