SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ACT_HI_PROCINST_View] AS SELECT ID_,PROC_DEF_ID_,NAME_,START_USER_ID_,START_TIME_,END_TIME_,DURATION_,DELETE_REASON_ FROM [ACT_HI_PROCINST];
