SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ACT_HI_COMMENT_View] AS SELECT ID_,TYPE_,TIME_,USER_ID_,TASK_ID_,PROC_INST_ID_,ACTION_,MESSAGE_,INTERNAL_COMMENT_,SIGNATURE_PAD_ FROM [ACT_HI_COMMENT] UNION ALL SELECT ID_, N'正在办理' AS TYPE_, START_TIME_ AS TIME_, ASSIGNEE_ AS USER_ID_, ID_ AS TASK_ID_, PROC_INST_ID_, N'正在办理' AS ACTION_, NULL AS MESSAGE_, NULL AS INTERNAL_COMMENT_, NULL AS SIGNATURE_PAD_ FROM [ACT_HI_TASKINST] WHERE END_TIME_ IS NULL;
