SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ACT_HI_TASKINST_View] AS SELECT ID_,PROC_INST_ID_,PROC_DEF_ID_,NAME_,DESCRIPTION_,ASSIGNEE_,START_TIME_,END_TIME_,DURATION_,FORM_KEY_,DELETE_REASON_,TASK_TYPE_,TASK_BLOCK_TYPE_ FROM [ACT_HI_TASKINST];
