SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RE_DEPLOYMENT](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[CATEGORY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[KEY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[DEPLOY_TIME_] [numeric](18, 12) NULL,
	[ENGINE_VERSION_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[VERSION_] [int] NULL,
	[PROJECT_RELEASE_VERSION_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[ACT_RE_DEPLOYMENT] ADD  DEFAULT ('') FOR [TENANT_ID_]
