SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_FGC_DELEGATION_CONF](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[START_TIME_] [numeric](18, 12) NULL,
	[END_TIME_] [numeric](18, 12) NULL,
	[USER_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[DELEGATION_PROC_TYPE_] [int] NULL,
	[ENABLED_] [bit] NULL,
	[CREATED_DATE_] [numeric](18, 12) NOT NULL,
	[CREATOR_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[LAST_MODIFIED_DATE_] [numeric](18, 12) NOT NULL,
	[LAST_MODIFIER_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[DESCRIPTION_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_DEL_CONF_ETIME] ON [dbo].[ACT_FGC_DELEGATION_CONF]
(
	[END_TIME_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_DEL_CONF_STIME] ON [dbo].[ACT_FGC_DELEGATION_CONF]
(
	[START_TIME_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_DEL_CONF_USER] ON [dbo].[ACT_FGC_DELEGATION_CONF]
(
	[USER_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
