SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_HI_PROCINST](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[BUSINESS_KEY_] [nvarchar](1000) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[START_TIME_] [numeric](18, 12) NOT NULL,
	[END_TIME_] [numeric](18, 12) NULL,
	[DURATION_] [numeric](19, 0) NULL,
	[START_USER_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[START_ACT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[END_ACT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[SUPER_PROCESS_INSTANCE_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[DELETE_REASON_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
UNIQUE NONCLUSTERED 
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_HI_PROCINST_START_USER_ID] ON [dbo].[ACT_HI_PROCINST]
(
	[START_USER_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_PRO_I_BUSKEY] ON [dbo].[ACT_HI_PROCINST]
(
	[BUSINESS_KEY_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_PRO_INST_END] ON [dbo].[ACT_HI_PROCINST]
(
	[END_TIME_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_HI_PROCINST] ADD  DEFAULT ('') FOR [TENANT_ID_]
