SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RU_EVENT_SUBSCR](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[EVENT_TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[EVENT_NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[ACTIVITY_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[CONFIGURATION_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[CREATED_] [numeric](18, 12) NOT NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EVENT_SUBSCR_CONFIG_] ON [dbo].[ACT_RU_EVENT_SUBSCR]
(
	[CONFIGURATION_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EVENT_SUBSCR_EXEC_ID] ON [dbo].[ACT_RU_EVENT_SUBSCR]
(
	[EXECUTION_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_RU_EVENT_SUBSCR] ADD  DEFAULT ('') FOR [TENANT_ID_]
GO
ALTER TABLE [dbo].[ACT_RU_EVENT_SUBSCR]  WITH CHECK ADD  CONSTRAINT [ACT_FK_EVENT_EXEC] FOREIGN KEY([EXECUTION_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_EVENT_SUBSCR] CHECK CONSTRAINT [ACT_FK_EVENT_EXEC]
