SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[需求详情_匹配供应商](
	[需求ID] [bigint] NULL,
	[供应商ID] [bigint] NULL,
	[模板ID] [bigint] NULL,
	[FGC_CreateDate] [datetime2](7) NULL,
	[FGC_LastModifier] [nvarchar](190) COLLATE Chinese_PRC_CI_AS NULL,
	[FGC_LastModifyDate] [datetime2](7) NULL,
	[FGC_Creator] [nvarchar](190) COLLATE Chinese_PRC_CI_AS NULL,
	[FGC_UpdateHelp] [nvarchar](190) COLLATE Chinese_PRC_CI_AS NULL,
	[FGC_Rowversion] [datetime2](7) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[联系人] [nvarchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[联系人邮箱] [nvarchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[查询方式] [nvarchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[任务ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
CREATE NONCLUSTERED INDEX [[需求ID]]] ON [dbo].[需求详情_匹配供应商]
(
	[需求ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [IX_匹配供应商_需求_供应商] ON [dbo].[需求详情_匹配供应商]
(
	[需求ID] ASC,
	[供应商ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
