SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_PROCDEF_INFO](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[INFO_JSON_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [ACT_UNIQ_INFO_PROCDEF] UNIQUE NONCLUSTERED 
(
	[PROC_DEF_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_INFO_PROCDEF] ON [dbo].[ACT_PROCDEF_INFO]
(
	[PROC_DEF_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_PROCDEF_INFO]  WITH CHECK ADD  CONSTRAINT [ACT_FK_INFO_JSON_BA] FOREIGN KEY([INFO_JSON_ID_])
REFERENCES [dbo].[ACT_GE_BYTEARRAY] ([ID_])
GO
ALTER TABLE [dbo].[ACT_PROCDEF_INFO] CHECK CONSTRAINT [ACT_FK_INFO_JSON_BA]
GO
ALTER TABLE [dbo].[ACT_PROCDEF_INFO]  WITH CHECK ADD  CONSTRAINT [ACT_FK_INFO_PROCDEF] FOREIGN KEY([PROC_DEF_ID_])
REFERENCES [dbo].[ACT_RE_PROCDEF] ([ID_])
GO
ALTER TABLE [dbo].[ACT_PROCDEF_INFO] CHECK CONSTRAINT [ACT_FK_INFO_PROCDEF]
