SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_GE_BYTEARRAY](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[DEPLOYMENT_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[BYTES_] [varbinary](max) NULL,
	[GENERATED_] [tinyint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[ACT_GE_BYTEARRAY]  WITH CHECK ADD  CONSTRAINT [ACT_FK_BYTEARR_DEPL] FOREIGN KEY([DEPLOYMENT_ID_])
REFERENCES [dbo].[ACT_RE_DEPLOYMENT] ([ID_])
GO
ALTER TABLE [dbo].[ACT_GE_BYTEARRAY] CHECK CONSTRAINT [ACT_FK_BYTEARR_DEPL]
