SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_GE_PROPERTY](
	[NAME_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[VALUE_] [nvarchar](300) COLLATE Chinese_PRC_CI_AS NULL,
	[REV_] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[NAME_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
