SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_FGC_HI_ADDONSIGN](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[ADD_ON_SIGN_TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[IS_COUNTERSIGN_] [bit] NULL,
	[IS_SEQUENTIAL_] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_ADD_PROCINST_ID] ON [dbo].[ACT_FGC_HI_ADDONSIGN]
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
