SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RU_VARIABLE](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[BYTEARRAY_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[DOUBLE_] [numeric](18, 12) NULL,
	[LONG_] [numeric](19, 0) NULL,
	[TEXT_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[TEXT2_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_VARIABLE_BA] ON [dbo].[ACT_RU_VARIABLE]
(
	[BYTEARRAY_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_VARIABLE_EXEC] ON [dbo].[ACT_RU_VARIABLE]
(
	[EXECUTION_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_VARIABLE_PROCINST] ON [dbo].[ACT_RU_VARIABLE]
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_VARIABLE_TASK_ID] ON [dbo].[ACT_RU_VARIABLE]
(
	[TASK_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_RU_VARIABLE]  WITH CHECK ADD  CONSTRAINT [ACT_FK_VAR_BYTEARRAY] FOREIGN KEY([BYTEARRAY_ID_])
REFERENCES [dbo].[ACT_GE_BYTEARRAY] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_VARIABLE] CHECK CONSTRAINT [ACT_FK_VAR_BYTEARRAY]
GO
ALTER TABLE [dbo].[ACT_RU_VARIABLE]  WITH CHECK ADD  CONSTRAINT [ACT_FK_VAR_EXE] FOREIGN KEY([EXECUTION_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_VARIABLE] CHECK CONSTRAINT [ACT_FK_VAR_EXE]
GO
ALTER TABLE [dbo].[ACT_RU_VARIABLE]  WITH CHECK ADD  CONSTRAINT [ACT_FK_VAR_PROCINST] FOREIGN KEY([PROC_INST_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_VARIABLE] CHECK CONSTRAINT [ACT_FK_VAR_PROCINST]
