SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RU_INTEGRATION](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROCESS_INSTANCE_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[FLOW_NODE_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[CREATED_DATE_] [numeric](18, 12) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[ACT_RU_INTEGRATION]  WITH CHECK ADD  CONSTRAINT [ACT_FK_INT_EXECUTION] FOREIGN KEY([EXECUTION_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ACT_RU_INTEGRATION] CHECK CONSTRAINT [ACT_FK_INT_EXECUTION]
GO
ALTER TABLE [dbo].[ACT_RU_INTEGRATION]  WITH CHECK ADD  CONSTRAINT [ACT_FK_INT_PROC_DEF] FOREIGN KEY([PROC_DEF_ID_])
REFERENCES [dbo].[ACT_RE_PROCDEF] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_INTEGRATION] CHECK CONSTRAINT [ACT_FK_INT_PROC_DEF]
GO
ALTER TABLE [dbo].[ACT_RU_INTEGRATION]  WITH CHECK ADD  CONSTRAINT [ACT_FK_INT_PROC_INST] FOREIGN KEY([PROCESS_INSTANCE_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_INTEGRATION] CHECK CONSTRAINT [ACT_FK_INT_PROC_INST]
