SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_EVT_LOG](
	[LOG_NR_] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[TYPE_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[TIME_STAMP_] [numeric](18, 12) NOT NULL,
	[USER_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[DATA_] [varbinary](max) NULL,
	[LOCK_OWNER_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[LOCK_TIME_] [numeric](18, 12) NULL,
	[IS_PROCESSED_] [tinyint] NULL,
PRIMARY KEY CLUSTERED 
(
	[LOG_NR_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[ACT_EVT_LOG] ADD  DEFAULT ((0)) FOR [IS_PROCESSED_]
