SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_HI_ATTACHMENT](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[USER_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[DESCRIPTION_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[URL_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[CONTENT_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[TIME_] [numeric](18, 12) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
