SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RU_TASK](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[BUSINESS_KEY_] [nvarchar](1000) COLLATE Chinese_PRC_CI_AS NULL,
	[PARENT_TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[DESCRIPTION_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_DEF_KEY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[OWNER_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[ASSIGNEE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[DELEGATION_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PRIORITY_] [int] NULL,
	[CREATE_TIME_] [numeric](18, 12) NULL,
	[DUE_DATE_] [numeric](18, 12) NULL,
	[CATEGORY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[SUSPENSION_STATE_] [int] NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[FORM_KEY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[CLAIM_TIME_] [numeric](18, 12) NULL,
	[APP_VERSION_] [int] NULL,
	[TASK_TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_BLOCK_TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[COMMENT_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[MULTI_GROUP_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_PARENT_TASK_INST] ON [dbo].[ACT_RU_TASK]
(
	[PARENT_TASK_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_TASK_ASSIGNEE] ON [dbo].[ACT_RU_TASK]
(
	[ASSIGNEE_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_TASK_COMMENT_ID] ON [dbo].[ACT_RU_TASK]
(
	[COMMENT_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_TASK_CREATE] ON [dbo].[ACT_RU_TASK]
(
	[CREATE_TIME_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_TASK_EXEC] ON [dbo].[ACT_RU_TASK]
(
	[EXECUTION_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_TASK_MULTI_GROUP_ID] ON [dbo].[ACT_RU_TASK]
(
	[MULTI_GROUP_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_TASK_PROC_DEF_ID] ON [dbo].[ACT_RU_TASK]
(
	[PROC_DEF_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_TASK_PROCINST] ON [dbo].[ACT_RU_TASK]
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_RU_TASK] ADD  DEFAULT ('') FOR [TENANT_ID_]
GO
ALTER TABLE [dbo].[ACT_RU_TASK]  WITH CHECK ADD  CONSTRAINT [ACT_FK_TASK_EXE] FOREIGN KEY([EXECUTION_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_TASK] CHECK CONSTRAINT [ACT_FK_TASK_EXE]
GO
ALTER TABLE [dbo].[ACT_RU_TASK]  WITH CHECK ADD  CONSTRAINT [ACT_FK_TASK_PROCDEF] FOREIGN KEY([PROC_DEF_ID_])
REFERENCES [dbo].[ACT_RE_PROCDEF] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_TASK] CHECK CONSTRAINT [ACT_FK_TASK_PROCDEF]
