SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_HI_COMMENT](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TIME_] [numeric](18, 12) NOT NULL,
	[USER_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[ACTION_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[MESSAGE_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[FULL_MSG_] [varbinary](max) NULL,
	[INTERNAL_COMMENT_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[ADD_ON_SIGN_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[SIGNATURE_PAD_] [nvarchar](max) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_COMMENT_PROC_INST] ON [dbo].[ACT_HI_COMMENT]
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
