SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_HI_ACTINST](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[ACT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[CALL_PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[ACT_NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[ACT_TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[ASSIGNEE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[START_TIME_] [numeric](18, 12) NOT NULL,
	[END_TIME_] [numeric](18, 12) NULL,
	[DURATION_] [numeric](19, 0) NULL,
	[DELETE_REASON_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_HI_ACTINST_ASSIGNEE] ON [dbo].[ACT_HI_ACTINST]
(
	[ASSIGNEE_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_ACT_INST_END] ON [dbo].[ACT_HI_ACTINST]
(
	[END_TIME_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_ACT_INST_EXEC] ON [dbo].[ACT_HI_ACTINST]
(
	[EXECUTION_ID_] ASC,
	[ACT_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_ACT_INST_PROCINST] ON [dbo].[ACT_HI_ACTINST]
(
	[PROC_INST_ID_] ASC,
	[ACT_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_ACT_INST_START] ON [dbo].[ACT_HI_ACTINST]
(
	[START_TIME_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_HI_ACTINST] ADD  DEFAULT ('') FOR [TENANT_ID_]
