SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RU_IDENTITYLINK](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[GROUP_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[USER_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_ATHRZ_PROCEDEF] ON [dbo].[ACT_RU_IDENTITYLINK]
(
	[PROC_DEF_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_IDENT_LNK_GROUP] ON [dbo].[ACT_RU_IDENTITYLINK]
(
	[GROUP_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_IDENT_LNK_PROCINST] ON [dbo].[ACT_RU_IDENTITYLINK]
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_IDENT_LNK_TASK] ON [dbo].[ACT_RU_IDENTITYLINK]
(
	[TASK_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_IDENT_LNK_USER] ON [dbo].[ACT_RU_IDENTITYLINK]
(
	[USER_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_RU_IDENTITYLINK]  WITH CHECK ADD  CONSTRAINT [ACT_FK_ATHRZ_PROCEDEF] FOREIGN KEY([PROC_DEF_ID_])
REFERENCES [dbo].[ACT_RE_PROCDEF] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_IDENTITYLINK] CHECK CONSTRAINT [ACT_FK_ATHRZ_PROCEDEF]
GO
ALTER TABLE [dbo].[ACT_RU_IDENTITYLINK]  WITH CHECK ADD  CONSTRAINT [ACT_FK_IDL_PROCINST] FOREIGN KEY([PROC_INST_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_IDENTITYLINK] CHECK CONSTRAINT [ACT_FK_IDL_PROCINST]
GO
ALTER TABLE [dbo].[ACT_RU_IDENTITYLINK]  WITH CHECK ADD  CONSTRAINT [ACT_FK_TSKASS_TASK] FOREIGN KEY([TASK_ID_])
REFERENCES [dbo].[ACT_RU_TASK] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_IDENTITYLINK] CHECK CONSTRAINT [ACT_FK_TSKASS_TASK]
