SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RE_MODEL](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[KEY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[CATEGORY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[CREATE_TIME_] [numeric](18, 12) NULL,
	[LAST_UPDATE_TIME_] [numeric](18, 12) NULL,
	[VERSION_] [int] NULL,
	[META_INFO_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[DEPLOYMENT_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[EDITOR_SOURCE_VALUE_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[EDITOR_SOURCE_EXTRA_VALUE_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[ACT_RE_MODEL] ADD  DEFAULT ('') FOR [TENANT_ID_]
GO
ALTER TABLE [dbo].[ACT_RE_MODEL]  WITH CHECK ADD  CONSTRAINT [ACT_FK_MODEL_DEPLOYMENT] FOREIGN KEY([DEPLOYMENT_ID_])
REFERENCES [dbo].[ACT_RE_DEPLOYMENT] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RE_MODEL] CHECK CONSTRAINT [ACT_FK_MODEL_DEPLOYMENT]
GO
ALTER TABLE [dbo].[ACT_RE_MODEL]  WITH CHECK ADD  CONSTRAINT [ACT_FK_MODEL_SOURCE] FOREIGN KEY([EDITOR_SOURCE_VALUE_ID_])
REFERENCES [dbo].[ACT_GE_BYTEARRAY] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RE_MODEL] CHECK CONSTRAINT [ACT_FK_MODEL_SOURCE]
GO
ALTER TABLE [dbo].[ACT_RE_MODEL]  WITH CHECK ADD  CONSTRAINT [ACT_FK_MODEL_SOURCE_EXTRA] FOREIGN KEY([EDITOR_SOURCE_EXTRA_VALUE_ID_])
REFERENCES [dbo].[ACT_GE_BYTEARRAY] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RE_MODEL] CHECK CONSTRAINT [ACT_FK_MODEL_SOURCE_EXTRA]
