SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RE_PROCDEF](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[CATEGORY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[KEY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[VERSION_] [int] NOT NULL,
	[DEPLOYMENT_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[RESOURCE_NAME_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[DGRM_RESOURCE_NAME_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[DESCRIPTION_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[HAS_START_FORM_KEY_] [tinyint] NULL,
	[HAS_GRAPHICAL_NOTATION_] [tinyint] NULL,
	[SUSPENSION_STATE_] [tinyint] NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[ENGINE_VERSION_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[APP_VERSION_] [int] NULL,
	[BPMN_GUID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [ACT_UNIQ_PROCDEF] UNIQUE NONCLUSTERED 
(
	[KEY_] ASC,
	[VERSION_] ASC,
	[TENANT_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[ACT_RE_PROCDEF] ADD  DEFAULT ('') FOR [TENANT_ID_]
