SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[系统操作记录表](
	[功能名称] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[用户] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[操作] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[内容] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[操作时间] [datetime2](7) NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
