SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RU_EXECUTION](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[BUSINESS_KEY_] [nvarchar](1000) COLLATE Chinese_PRC_CI_AS NULL,
	[PARENT_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[SUPER_EXEC_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[ROOT_PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[ACT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[IS_ACTIVE_] [tinyint] NULL,
	[IS_CONCURRENT_] [tinyint] NULL,
	[IS_SCOPE_] [tinyint] NULL,
	[IS_EVENT_SCOPE_] [tinyint] NULL,
	[IS_MI_ROOT_] [tinyint] NULL,
	[SUSPENSION_STATE_] [tinyint] NULL,
	[CACHED_ENT_STATE_] [int] NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[START_TIME_] [numeric](18, 12) NULL,
	[START_USER_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[LOCK_TIME_] [numeric](18, 12) NULL,
	[IS_COUNT_ENABLED_] [tinyint] NULL,
	[EVT_SUBSCR_COUNT_] [int] NULL,
	[TASK_COUNT_] [int] NULL,
	[JOB_COUNT_] [int] NULL,
	[TIMER_JOB_COUNT_] [int] NULL,
	[SUSP_JOB_COUNT_] [int] NULL,
	[DEADLETTER_JOB_COUNT_] [int] NULL,
	[VAR_COUNT_] [int] NULL,
	[ID_LINK_COUNT_] [int] NULL,
	[APP_VERSION_] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EXEC_BUSKEY] ON [dbo].[ACT_RU_EXECUTION]
(
	[BUSINESS_KEY_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EXEC_PROC_INST_ID] ON [dbo].[ACT_RU_EXECUTION]
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EXEC_ROOT] ON [dbo].[ACT_RU_EXECUTION]
(
	[ROOT_PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EXECUTION_IDANDREV] ON [dbo].[ACT_RU_EXECUTION]
(
	[ID_] ASC,
	[REV_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EXECUTION_PARENT] ON [dbo].[ACT_RU_EXECUTION]
(
	[PARENT_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EXECUTION_PROC] ON [dbo].[ACT_RU_EXECUTION]
(
	[PROC_DEF_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EXECUTION_SUPER] ON [dbo].[ACT_RU_EXECUTION]
(
	[SUPER_EXEC_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_RU_EXECUTION_START_USER_ID] ON [dbo].[ACT_RU_EXECUTION]
(
	[START_USER_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_RU_EXECUTION] ADD  DEFAULT ('') FOR [TENANT_ID_]
GO
ALTER TABLE [dbo].[ACT_RU_EXECUTION]  WITH CHECK ADD  CONSTRAINT [ACT_FK_EXE_PARENT] FOREIGN KEY([PARENT_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_EXECUTION] CHECK CONSTRAINT [ACT_FK_EXE_PARENT]
GO
ALTER TABLE [dbo].[ACT_RU_EXECUTION]  WITH CHECK ADD  CONSTRAINT [ACT_FK_EXE_PROCDEF] FOREIGN KEY([PROC_DEF_ID_])
REFERENCES [dbo].[ACT_RE_PROCDEF] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_EXECUTION] CHECK CONSTRAINT [ACT_FK_EXE_PROCDEF]
GO
ALTER TABLE [dbo].[ACT_RU_EXECUTION]  WITH CHECK ADD  CONSTRAINT [ACT_FK_EXE_SUPER] FOREIGN KEY([SUPER_EXEC_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_EXECUTION] CHECK CONSTRAINT [ACT_FK_EXE_SUPER]
