SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_HI_VARINST](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[VAR_TYPE_] [nvarchar](100) COLLATE Chinese_PRC_CI_AS NULL,
	[REV_] [int] NULL,
	[BYTEARRAY_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[DOUBLE_] [numeric](18, 12) NULL,
	[LONG_] [numeric](19, 0) NULL,
	[TEXT_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[TEXT2_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[CREATE_TIME_] [numeric](18, 12) NULL,
	[LAST_UPDATED_TIME_] [numeric](18, 12) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_PROCVAR_NAME_TYPE] ON [dbo].[ACT_HI_VARINST]
(
	[NAME_] ASC,
	[VAR_TYPE_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_PROCVAR_PROC_INST] ON [dbo].[ACT_HI_VARINST]
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_PROCVAR_TASK_ID] ON [dbo].[ACT_HI_VARINST]
(
	[TASK_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
