SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_RU_JOB](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[REV_] [int] NULL,
	[TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[LOCK_EXP_TIME_] [numeric](18, 12) NULL,
	[LOCK_OWNER_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[EXCLUSIVE_] [bit] NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROCESS_INSTANCE_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[RETRIES_] [int] NULL,
	[EXCEPTION_STACK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[EXCEPTION_MSG_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[DUEDATE_] [numeric](18, 12) NULL,
	[REPEAT_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[HANDLER_TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[HANDLER_CFG_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_JOB_EXCEPTION_STACK_ID] ON [dbo].[ACT_RU_JOB]
(
	[EXCEPTION_STACK_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_JOB_EXECUTION_ID] ON [dbo].[ACT_RU_JOB]
(
	[EXECUTION_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_JOB_PROC_DEF_ID] ON [dbo].[ACT_RU_JOB]
(
	[PROC_DEF_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_JOB_PROCESS_INSTANCE_ID] ON [dbo].[ACT_RU_JOB]
(
	[PROCESS_INSTANCE_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_RU_JOB] ADD  DEFAULT ('') FOR [TENANT_ID_]
GO
ALTER TABLE [dbo].[ACT_RU_JOB]  WITH CHECK ADD  CONSTRAINT [ACT_FK_JOB_EXCEPTION] FOREIGN KEY([EXCEPTION_STACK_ID_])
REFERENCES [dbo].[ACT_GE_BYTEARRAY] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_JOB] CHECK CONSTRAINT [ACT_FK_JOB_EXCEPTION]
GO
ALTER TABLE [dbo].[ACT_RU_JOB]  WITH CHECK ADD  CONSTRAINT [ACT_FK_JOB_EXECUTION] FOREIGN KEY([EXECUTION_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_JOB] CHECK CONSTRAINT [ACT_FK_JOB_EXECUTION]
GO
ALTER TABLE [dbo].[ACT_RU_JOB]  WITH CHECK ADD  CONSTRAINT [ACT_FK_JOB_PROC_DEF] FOREIGN KEY([PROC_DEF_ID_])
REFERENCES [dbo].[ACT_RE_PROCDEF] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_JOB] CHECK CONSTRAINT [ACT_FK_JOB_PROC_DEF]
GO
ALTER TABLE [dbo].[ACT_RU_JOB]  WITH CHECK ADD  CONSTRAINT [ACT_FK_JOB_PROCESS_INSTANCE] FOREIGN KEY([PROCESS_INSTANCE_ID_])
REFERENCES [dbo].[ACT_RU_EXECUTION] ([ID_])
GO
ALTER TABLE [dbo].[ACT_RU_JOB] CHECK CONSTRAINT [ACT_FK_JOB_PROCESS_INSTANCE]
