SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACT_HI_TASKINST](
	[ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[PROC_DEF_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_DEF_KEY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[PROC_INST_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[EXECUTION_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[NAME_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[PARENT_TASK_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[DESCRIPTION_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[OWNER_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[ASSIGNEE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[START_TIME_] [numeric](18, 12) NOT NULL,
	[CLAIM_TIME_] [numeric](18, 12) NULL,
	[END_TIME_] [numeric](18, 12) NULL,
	[DURATION_] [numeric](19, 0) NULL,
	[DELETE_REASON_] [nvarchar](4000) COLLATE Chinese_PRC_CI_AS NULL,
	[DELETE_TYPE_] [int] NULL,
	[PRIORITY_] [int] NULL,
	[DUE_DATE_] [numeric](18, 12) NULL,
	[FORM_KEY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[CATEGORY_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TENANT_ID_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[TASK_BLOCK_TYPE_] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[COMMENT_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
	[MULTI_GROUP_ID_] [nvarchar](64) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_HI_TASKINST_ASSIGNEE] ON [dbo].[ACT_HI_TASKINST]
(
	[ASSIGNEE_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_EXECUTION_HI_TASK_INST] ON [dbo].[ACT_HI_TASKINST]
(
	[EXECUTION_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_TASK_INST_PROCINST] ON [dbo].[ACT_HI_TASKINST]
(
	[PROC_INST_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_HI_TASK_MULTI_GROUP_ID] ON [dbo].[ACT_HI_TASKINST]
(
	[MULTI_GROUP_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ACT_IDX_PARENT_HI_TASK_INST] ON [dbo].[ACT_HI_TASKINST]
(
	[PARENT_TASK_ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[ACT_HI_TASKINST] ADD  DEFAULT ((0)) FOR [DELETE_TYPE_]
GO
ALTER TABLE [dbo].[ACT_HI_TASKINST] ADD  DEFAULT ('') FOR [TENANT_ID_]
