SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[询价列队表](
	[需求单ID] [bigint] NOT NULL,
	[询价任务ID] [bigint] NOT NULL,
	[供应商ID] [bigint] NOT NULL,
	[目标邮箱] [nvarchar](500) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[邮件标题] [nvarchar](500) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[附件内容] [nvarchar](1024) COLLATE Chinese_PRC_CI_AS NULL,
	[邮件内容] [nvarchar](max) COLLATE Chinese_PRC_CI_AS NULL,
	[发送状态] [int] NULL,
	[错误信息] [nvarchar](1024) COLLATE Chinese_PRC_CI_AS NULL,
	[发送时间] [datetime] NULL,
	[顺序] [bigint] NULL,
	[FGC_CreateDate] [datetime] NULL,
	[FGC_LastModifier] [nvarchar](190) COLLATE Chinese_PRC_CI_AS NULL,
	[FGC_LastModifyDate] [datetime] NULL,
	[FGC_Creator] [nvarchar](190) COLLATE Chinese_PRC_CI_AS NULL,
	[FGC_UpdateHelp] [nvarchar](190) COLLATE Chinese_PRC_CI_AS NULL,
	[FGC_Rowversion] [datetime] NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[模板ID] [bigint] NULL,
	[报价ID] [bigint] NULL,
	[抄送邮箱] [nvarchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[父ID] [bigint] NULL,
	[MessageId] [nvarchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[回复对象] [nvarchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[发送次数] [bigint] NULL,
	[无效标记] [bigint] NULL,
	[类型] [nvarchar](100) COLLATE Chinese_PRC_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
CREATE NONCLUSTERED INDEX [[报价ID]]] ON [dbo].[询价列队表]
(
	[报价ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [[供应商ID]]] ON [dbo].[询价列队表]
(
	[供应商ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [[模板ID]]] ON [dbo].[询价列队表]
(
	[模板ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [[询价任务ID]]] ON [dbo].[询价列队表]
(
	[询价任务ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [IX_询价列队表_需求单ID] ON [dbo].[询价列队表]
(
	[需求单ID] ASC
)
INCLUDE([ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
ALTER TABLE [dbo].[询价列队表] ADD  CONSTRAINT [DK_询价列队表_3bd6664fc1a24ab3b386229c48db3129]  DEFAULT ((0)) FOR [发送次数]
